baseURL = "http://localhost:1313/"
languageCode = "es-ES"
defaultContentLanguage = "es"
title = "nowfreelance"
theme = "ananke"

[languages.es]
languageName = "Español"
weight = 1

[params]
custom_css = ["custom.css"]

footer_tagline = "Ayudando a empresas a crecer a través de la automatización y la tecnología."

[[params.social]]
  name = "LinkedIn"
  icon_name = "linkedin" 
  url = "https://linkedin.com/in/"

[[params.social]]
  name = "Twitter"
  icon_name = "x"
  url = "https://x.com/"

[[params.social]]
  name = "YouTube"
  icon_name = "youtube"
  url = "https://youtube.com/c/"


# --- MENÚ PRINCIPAL ---
 [menu]
   [[menu.main]]
     name = "Inicio"
     url = "/"
     weight = 10
#   [[menu.main]]
#     name = "Servicios"
#     url = "/servicios/"
#     weight = 20
   [[menu.main]]
     name = "Blog"
     url = "/posts/"
     weight = 30
   [[menu.main]]
     name = "Contacto"
     url = "/contact"
     weight = 40