baseURL = "https://nowfreelance.com/"
languageCode = "es-es"
title = "nowfreelance"
theme = "ananke"

[languages.es]
languageName = "Español"
weight = 1

[params]
custom_css = ["custom.css"]

[development]
baseURL = "http://localhost:1313/"